<template>
  <div>
    <!-- Header -->
    <div class="px-30 py-10 text-center">
      <div class="link-effect font-w700">
        <svg
          width="232px"
          height="68px"
          viewBox="0 0 232 68"
          xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          version="1.1"
        >
          <!-- Generated by Pixelmator Pro 2.0.1 -->
          <defs>
            <image
              id="image"
              width="232px"
              height="68px"
              xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUwAAABYCAYAAACeXs5mAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAABTKADAAQAAAABAAAAWAAAAABsi0BDAAAlZUlEQVR4Ae1dCXgURRZ+1TOZBAIEOSOHnIrKTcBdlQU8EdxwhEMQuYTVVXTVRddjVwVhV11dz/UAlWtZBQKEBBFxXYwgomC4cQHllvvMQUgy0937V0JCju6Z6WNmOqHqy2S6q+q9evWm+vWreq9eMXJyeuz6anQVq0nRJ2uQ2xNN+Z4oogIil+ojb0w+eaRzVHAoi+4/fB7dUJ3cFUGb4IDgQOXnAHNAFxjN7BRHTG1MJHUgRe1EknQNEWsK2upBDsbgG4KS3MQYI1XlNCv4yPgUEOMSlE5AXO4hRfmJJLadJHkDeWvup3vX5KBcCFIwSCTBAcEB6xyInMB8t/1lFOO+BQKuP7rRA4KtKUSbXfT4gPMAPt9CHV1K56PS6YFvj1tnl8AgOCA4cClzwC4BFRwPuZD0RHUnF40kSelOqtQQgFJwwKZrcW30JDTWVdBQ55P7+H9pxIEzprEJQMEBwYFKw4G+ffvGR0dH10pJSdllB9HhEZgzurUkl3IfptfDoEU2s4NwCzh+Bh3/IRd7jUZuwLVIggOCA5WdAwMHDqyLPtzmc7maSbLc2sVYe5+qtoSAq4/rWYsXLx5rRx/ddiDRxMGn1/MTWmKFcRzJ8qMQlNU064U/szW0zdbkU8fSjE5vUZT0gRCc4f8RRIuCAyY4wHolJTWOk+W2EIytJFLauhRqpTLWVlbVxjBxMAjLQrS4t219rzSdodEwZ/aCoSbzEWLSn6DN1SndoAOvj8LgNIuUuMk0Nj3PgfQJkgQHLnkOJCYlPSqp6gtgRE2jzLBTw7R3/XDSJIlmdRhHLOt/WC98qRIIS877eFLZUyRl7aDZXe6h+xK4RV4kwQHBAQdxAJpdbZBjWFja3QX7BOZHbRpR87SX4f3zPohsbjehIcfH11ZV+oC6K28SN06JJDggOCA4UI4D9gjMGZ1vJVfsOuB+HJ/QrYuWIz4EtzGksAco1rONPkq46YLPZwiaESgFBwQHKiMHrAvM2V0egi9lMjoPx/MqklS1EVyfPqd/dX6kivRIdENwQHDABg6Y1wYXQKTkdnkD09iHbKDDgShUDynS6zQzIZ6yM/9Gf/g5y4FECpIEBwQHwsgBcxrmtIR6dK7rdND5+zDSGpmmmPok1azxFhVa/iNDgmhVcEBwwBkcMC4wueCIkT8iptyLLpjXUJ3R/+CoYNIouEktorc61w8OQNQSHBAcqIocMCYwpyXEkSt7GqbhiVWRGX76xOAm1Zdqq6/TtMJAIH6qiiLBAcGBqsoBYwLTo05GNCFoW1JoHN6dzmVFGk4xCR84nUwr9PXq1cuNT8wk7lMrkuBARQ4wPj74OKlYVPVzguv0JDDniqw/Yq/RgxFhSQw2C9VqAtfV1tSvTivqHF2H4qNrwOrE6KyST7vPZ9K03CNEp7A1/PROotwTCADnDQWpElyNRmBL5U66d9OLoWggnDgHDRrUVZKkm7ykJEgqS0Db8fjU4DRs2baNkgYPzmGqehJbz35RmPqzylwbPaq6Pjk5eS2v46Q0ZMgQV35+fgf059eKy9XBrarxKt9LzFh1Tieu+S6uU/g+jLwduOZucOsRlOEUvkUqx4E+ffpEx8TEdAO/bkBRR/CsC7Yb1sM391F28eqJSQN94OxhbE/8WXa5NkeparrP5/sqLS0tm5dXxRScpjizSyJkUwoYUMiosDBCwoabZj3piSt60e8aJlCrag2CCmt00ptDGVkH6Y4j3xBtX0iUh0BF9qccUlwP0L3r59qP2hxG/savU6cO30/LhUYzCI/ZWgN3wIABtd1u98NoZRTCOLU21xodR+zRz4HnXwsWLPjSJA7LYFwLXr9lS08Ix5GqJA1gimJ4wwHU6DXg2SyXy/UFXgQHLBPlAAQQdrU8Hk8z9IsLumN4KfwnGLJGjhwZm5OT01uWpBHg5S2AiQsGrlydXGxFXKAoyuQlS5bsK1dm+rZfUtIkvLyfN4PAzq2RgQXmJ92aUr68FYSaYZ7x/nFB2boPbWg/jjrXaGIcvhREHrTMNw+tpqe+ewVa5/FSJXZcKtkkedvRqO0ReciGDh2aiNf7dSoprZhCnZnEmqtKYbDlws5JEktrd23bgRAqPLwdcUHJoqMf44FQ8KPXsoMDHAc0z91Yopm6JDl5ll04A+FJTEysHhUV9QDmEBOwv7hFoPpBlst4sP5l94MeZNumqiEQRZPaitLex1hLvCTbSYpyFaJlXw1kjYoRQkM86c3Pb7V8+XJdtzhE+mmnSNJovATHA45vQbQnKcpLmZmZz6anp2OoBk59Bw68zS2xOVo1maLymU/h7EerPEBejiqxnAB1CosRkbz354sWbdGr619gftSmJkm1konJvfUQ2Jpf91qa2+0RGtYgAdHX/JNmpN0ducfomh//TfTjPMwgiqKZGIHXrSvTArq84Sjquzxft06ICjBd/h9Q84dDN7kl6W1ogH8YPHjwMDw4b2Jq3UC3ssUCPKg7IYz72RV3UI+cpKSkwZgavoHyxnp1bMifhvE3FSHBfrGCq//AgXsBb0oAQZsaCA0t3V/7wA+2B07oy3Poy5TyNSEouwPBc/jcVr7MrnuMu60QxHdgtnM4EE7Qcwfe7ssD1QtluUT0EMbwO3ptoNxPcld7GMLydj817CmSook6jKGcPh/SiIZdbRWWnMCrqzcktesf6ePe72L7vjWttUyHXTSUjh97tkyeg258ivIwBOt6DMJPQikseZfxemvDXK4dSUOHhoQfEJSXQ0Ash7AMx66y+9HON3iAh1n8ObmwNPWBphtjse0ScPTlj3yGUZxx26BBV4KXn2JcrA6lsOTtYUmgPcbFF/369atZ3L7Dv6/zR5++wFzQC1F8pKd4n/0hsKPsnl9NJLXzwxTrguAMYRoOYfztrW8Q1bnSzlYepdkdQ6ntWKW1q1UEBuAZtIkXBg4dOgNGGI8BOL9V+/fv/ys89D+g0h1+K9pb2Iy/aCA0pwJtyJ8Be0mvgK021hsew29SY8DgwVOqqyqfct5ZoVboMtpCaL4WOvT2YcZvfrM/bPoC81wmJEuIwylF1aCHfzOZ/nXVIH802lp2fa0WdLT3B4jD3N4uvLGkuqfSZxRaaW8XtWHAA4PBWES7/swOoQnNaBwOxVsFskvW5cLQhZIm8AD9eUBSUmol0pBKaC99AYn/qNfn26DK8l/gMmCb9lq6jQDX4+GVcWuAOk4obsKPtdAjRFtgzuzUF7p0oh6QLfnMTX++/hl6tUVwSkO2nE9fndlFQ3YtIJbxOrHVz+CUnqeJfT+VYrZ/SP84mE67gjTsNPTUpC09/wZNs7UtXQGSUXSsS+iXLuyiNgx48IDeAnelD600Be1uApYSOA7btFUz9GAdLrGSTSsrdBOGwVqYfts6tarQSIAMzBJeRRXHa+twp+qp15WKApNHdmfSiwAo9F/TA7Scf3V/mtqiN3kgOP2lXKWAHtidRrW+mEA3fzqSFq5FyM1tc4n2rCDa+wXRjhTK/+E9enzlRGrz2Rhim96l1Zm7cQ4vhoef1D62Ec29DtHouI+n5aRKeMFMJu6vKlIJB+DbOXLQXUP4so7hBGHZDtrd24YBQwfwawjNT4De8Q986FhgDTNePB2hZfaxhiX00HjR36jXSkWBOavLb1HZtvmqZsNYQ9zX4X7NouJMMJfeOvwNxa54gN5fM5Xo+Eb4sATwTjh3jGjzR9Rj2VhybXiDjnv9+88Ob9iNhne5r7hJa98M56k3Oyu0zHJcVGV1CqbVCeWy/d6ifnMIy09RyWnC6c7+gwb93S/xotAvB2CIhJbi7MSYizvra6ayAvOzPtHwDn8UNUM4UBk0u4nULKauJkE8k2uVEjTFR/4L3h7fZNwVyHuOaOtcavifhyj11Dbddnjn32uBte9Gv9atE3RBoWZOT4ioRhU45pbc7rcq5PrJgGUVU4iIny6qTSEeeBihBmoXitwgOND9zjvvNLzBIAi8tlXBGnx7biDTQlhWYJ463hYzWb9mdS0khvKa3UR3N+iqC8KdzWM3vg+BN9P69sYT22hA+tO0OfuQbntx7uo0o/1o3XJjBRLOXM9sZwzmkqh9A3xB+cwlYIIwehzape6UKCCCMFTArqJpvXv3tmMtJwzUOq4J7DmICs5wETnSPedVVVNIlRWYsnI3aNSUrLbQDreh+W1HcN8sXXTVtkNQbp8DrdL/GqQugvIFOYepU/pE2s33l+uke+LBm3ptdUoNZbtJpuGGICJcGQ7S6QopT2Ig9MV1Nzg5/0ZmbASuZ4C0A3aRhyWWpwPh4lNxWMRNrXmWxo2RsxntvYm+/A79SkRfbsL3AOB+GtfcMfp86fpGrzF660fXqPGCUbhKVL8AfPoGPHsdu4gmcD7C+PYcnttvbemDJOlOeW3BbwOSKFnWfGlfNFL887q6pHqTQjkZpzpX04B6+gpYygm4h22ZY5+wLGbc6Z+o9fpXqaDni4jNhmFQLvG8FzqMpudW/qlciYlbxpJoTquXadRuu/dimiDGL0gaHopJixYtwuKwZvr4wv70RyBoJqNGrGatIDPxwN0AQ05P7KL4Wg9EcbFnYc3VX6vRA7yQDyG5AH16LS019XudqqnIf4lPCaOjowfBavtn3DfXqes3G9O2B6ANT0tNTd3qt2IlKsSL5mtu2GI+33zsMjqrQfoUbCC428fU97jVXaM8qCz8Th20KnpdrjyXLGu1i0VCFmPaHYqxPMDmabWplwcaNe04FwVm7YLe5OODh+nhsJzfplkPv1bxpE3vEfksvfz1adz3Jb3T6k56tEkPzTrjEeDjudiGRNxwZCWp8BeUanNL4GwraEIJC188v9u/itu+sAf4H33vumtpjCyvRH7j4jIz3whwMQBwX2vBcu1SVWiMVlmgPGg+e/EaHLk4JWVNoLq8fNmyZWfw9SHWqRbne71cc3okGLhydSTAPYG8UeXyK+Pt5+DfS/5eZsWdwhbLj/Fb5eMFuLA4z8T3VVowny5cmI58zfXNwuAbRM9rwQXKQ8SgeRgbYwPVC6b8orrldQ0NaZxL5qLpjbvr0vTCgS+JDq/TLbej4LGtsynLp/2iudxTm6jJ9dabYfAZlNV+TnYxyne7ETAj+PTZ/Pm7oLklYrBoMy9IVArRML2qeKOPR9nF8ahXsVw+Xu/rZa/3OjzIQQnL0uCITnQ6bcmSR7E7iQs+wwlCYwiEBwZOpU1fRblcN6ampPQJRlgW9xLa5yKMh/TiexPfDRMSEqJMwEUcpGiAzsZ0nGmroLZRGNeCro2N10X3/E98thTiBIv7ppyDuo38vn5H3TJDBQp1pzqZmm9KQ3gcVJlP3QtIeckiSfHww7tSEwdCimnm+8/cnp+Xd+vSpUtP+q/mvxTT6lcVxh7zX0uzNMarqv794zTBIpsJzfgHPPi3QFDevHDhQlPrklg++dhCL1izZs3qWYCPGGiRwFQLrsZMvEVIqWjYjuKiqms2sf3cESJYtMOR7jukr4j0iWtpDwmMGmBfhea0w54GIoMlmrn+gTBZfDprOsGI0LM8MLYd8gX25uXzA9wfhJbzW39hywLAlyleunjxGwhxZsj9iSNwSdJvyyCqBDfQKntAo+RLLKaTWuDDlNBS8liCjhBwkcAk9Tq4E2F2E7rUvkZTTYMLb/H7rP1E+Vmha7wU5p0nfyx1V/aycw1LS3Rlkalux1sCyxIc+A5T2BxFkbHQbD4h2G9FNd7tNuxmgoE7yc4AtbxHMZL0HF4IR430Dg8NN2aZNlQZacuuuidOnIB9x1rKzs4+qDBYPUwmaLnVTIJGFKxIYEpM0+fITspurKa/1PPdeUNj1BpZZ/frbptsFA0asdZqS5KUX9uCx2FIPMxlbe2EseYVusSoR4U8Pxl42vdAQ5rhp4qpIrwQMjEAXjEIjLi9iiH6DeJ3ZHVuEJRUa2vajuxYAKIkWjDEheMWKr71AwAaLY5363ulrMOZPGFLvlzK0TH8wN8MBwfr02mIRoWuDbXWboge+ypnwECTbRadoqptysMimrahFzZeaVbXUsuTUHLvzc39EFqmoQEJfnQuQXBpXZjWMCsrmyQ6dQj+l+zyUHcAKrhuE5tlr25ZKApkf4E5/NBpiBZGdWj6NfpWLkPInFMZWpgMf5pdZinCOLisNCzOn2mCe+3F7dIVS11nqqql9bdSqCpc8jVRheirCgV+MlS31MpPsSiqQhyQcKxZI2KKs9cTqtfHKTRNscjEnzV9wRvU7+KOoVquGM2qMhwBCRqoTakWSdVAeBVMqrrTQq/KrM2oMTHNDeLav3LJEkNuUQbxw2FE21dUDw+iMtlkLdRrQeQ7hQMSec7zBWtnCkwJfvUdxtKexH+Tb8Bi2t9vPvW67lFMm7UFXlBMxXG9LnbB1lUO4EgBZmJ2Hc/LEFDYo9poRSpHbARvMQW1srvATWPGlPyAMapa00hXYBkPqbAspIWxfYZoYqxSusgY6aOoW8QBfs42trc4M0V3+R35Ok2gFohsxIXcFdXq0lfX3EMdO91nnuC6bXVhM/z4aOoC6RVwrwPFubzVIzuYfEyrzwVTL5g6OM86Oph6xXXgLH66+DpU35LPd9wIbrxALu6YMwIo6lY6DkikeJzpEoHjK9Y26615INqKKweatGYzmn+5vn1h6Zm99v6AkqtKRrSBgDAk5MozNWHrVrl8npPu8UIw5COI+pec8cNJv1c4acEaZoHpTfQhJdQTS425m49GaugByThmwnBq0J761LlGF+yjoxm6ZaYKFNWZvDXVmYtAistlZQrqy8jIKLHyQTIZmt4jtFqLi5SE5kpxu4296BScUS/SJcEBLObpWEAi3f2Cc3Qo/6wmFccK4OTO1xsNpn4t76CaOjPATC+e21NWbBkaxJxTDGkqGhgcmSVZW8Yp86MWFBTsN9JJRAm6ikdRMgJjtC6T5QSDMJZ2PxlsS1SPIAewhilrW0AiSFRh094c6vLjXDrNo6eXSuflAorPeMN4CLjGN1Bym8GlMJW9nHniB6KzNtsTfPnO5G3Zrpu50wx9FQwi+Dj8UroeIhgdLX0fxHXNyy67LNSbAm4Ogo6SKlhXNST0SwDFRaXjAB5o5tz1JBxwVnfNZPry9A7yIjLvt5l7qPqqZ4h2pRpjNLY8bsMJlR74UOmlx3CkBaSwXrG5/Nho5/LWXI8IwTM6ADTOJDh2WVEZg8qFuIuHjeCDoWiAkfpG6qJ/LVHfmEBWlK1G2hB1Ky8H3LDk5sGy4sweqJA3+/9Lt+FjOrmr0YKek6ltrL5v/tJT24mOQsO0OzFmaH3O7uZDgQ/rl7djWmwaNabzW8oDuyVpDQ7HGlI+X+8eU+bxOCLibytWrDitV8dsPuj4i1FYHLnwvVEYUT98HICRsoZdrcHo4za+GGhX66HGU7sFzbv9LRpSr7NuS/mqj/ptmq5bbqkgipVZr7OEyyHAqipPsEIKLMoVLGter3eVQZxxoTgi4oJ2OdYgLWfbtWv3nUEYUT2MHIDAbG1XcxLijZyyC5mj8DS7mY73mUl31e/il6yp+1cSHVrrt47pQkU6aRrWgYCIUD4Gu1qaWyENg7eCwAS+ZKM4oeVOQJSg/kbh9OrzQMA4suJLvXK9fDjSr5g0aZJ5lVsPscgvwwG8aPPKZBi4wRrzNXYFesYapszXj2xevDPQGzurclejpr+h927/J2V2n0L1A7gefZ35M03dDO2ST/3tTgw8dSll1uvsbiKc+CAsr8AB989baRPCZRcCEf9UHkdaWtoxlKWXzw90D+E7KzExUX8nQiAEF8rRNw9Mn/8GvhZBgpRU80nS/JIbcREyDsjWXLeiIXDvtYM4N8KZHcMG6hycDgBpY0OKguth/WuBrqyBpUW0vp3g2bgraAoEneHEA2VExeJ4rob0l8uuohENOlKbag39nkpZ3MYv+Weo1zcvwDK+tzjL3m8V/oVRMnhb+RMXKD5VnSsRa26xN//Rg8eAnoa3di+9cq18aA613W73KhzMNR5HVKRo1QmUBy21gc/nS0bfegSqq1G+71OT7WrgEll+OICxYWkmjCnAn/Bbz0VYwIBKDNdG8fJ8TJKkeaj/v9JkuammepRyGY84YY/AvKwlnb/lTQRjDd5V7oVmtxP/hCudgMtS0+9eIjoJY0/oUg5lux0pMD2kjMSg2BFMAF4eHBfCcj5eTSbeaGWZi7OEPiibc/EOgm9xgc93BDn61rmL1Uuu8CDUwfbexRCa/5Rl+e84buJgSWGACz6lB/y7qNYoQFXNYoQDfEWzQGTazgGcJrmRXGWVMIONNIQQXIHoWImISFXGta0YDxSDOhhDf8DSzCPQumojzin3o366uJx/u2loRibN6sKn5Q1LF5i+rhFvSFiabsck4P6809Q8400inCIZ0sToCN2XcYruD2krppBjHfJucrv7wcixEJrdB1rnuvC3LKy/92Lw/AmNWB4bTGLrP50/f7MewQgbV3DnoEFT3IrCBZjhBDofwnHAwxKTklJxTOz7mOZruj30Gj68XlxB3l0u8AAwNxhu6CLAPviQzrl4K65CyYGsrKzdterWyUTsVP2pagACMCPp5ImJWf3bQYP+4ZbltRjfO/Pz82upUVHdoRDcXSDLvcsc5StJv4eAfbH0MSgX1EBpPcL06JuSAxBSpjiuaZlbJ92szdpHN6Q/SXTm5zCQBeMGX8d0bqqBATQGBI4ZNHRIlqqoWzBoTuHeC+HGDyprIytqSVQhq93AQH8tEI5u7dtP27B16zgYdIzutClGXQ9uS+OgiYzrP3DgaYmI+0eewDna5104RxsHnbVneXkteWW/MVGLsfn5Bu4p/MgOP1VEkY0c4BHe8TJchTGaaBFtc5eivI2xT5jRYEXSheiWmGdop9pS9erDUFTiRlMkMBXaYPyAU+0Wnqh1hXZBBHNzlQL6457PaVrG2zgo1nbXPe2e+WiTdoHzciEssfBM3YulO+7tJvIHaLHzAiHl1mZovRN8RPykOkvzL8DXwWPQk7cJjRoxsi1HUuWoipJEX6Qssv+IjGL04lubA5Is/xuzCKsCUxu5Tm6ULI9EUYnAxIsSySOvxn+MU+upd1wr60hswpDlO08vH1xJscvH0jTsGAqbsOQKjEtZaVM3KjUaHJSlwgJ+V7CdgBX9ewi654OtH4F6B5lc+Y7WjQCfbG8Sa4pLgTSsrnrQRLvjVNMexZ0pEpiKvB/v34PFmVa+/Z09bgWvEdjj3mx6ZO+nFLd8PD319V/A4h1GwO2o+xNV94GnIrkUdRKE4B4jnFiakvJXGFSWGIEJU10VD8yYYIxlYaLnkmoG58/nQoDBWhvepLrdY4tbLJqSj9pyjuZ0/pwU9kBxgalvrAs0WqdjOESotrOdH6Q4d/UKqI8VZNOePHNeA17FR0e8WbTu3FF67fTuIsv30Y3wrbRFYa5Aa1AZKmXQ0O2X/PoWNMsFEJYvBMWzcpVgUBlToMgbIXBblCuK3K2iTExJTRUzh8j9AhTtcr2Rp8jDJIMH51khOYpoCIygj/G4BxeMPkCn0CL855LU/EK/irWv3cu1aavRiLI7jNMUmF12LaTDW2ZqwwXK5YIREYxg3QpUM1zl+SS7PwlXY05tBwaWzUpBwXiz9PEjbzFIb4ZG8RVwNDeLxy447DF/allq6ut24RN4zHGAH8KHcTEM4+J7YKhrDosxKHhTxGKDwoOA+lvRlJzDN4j/BtNyqGjhT4cVGbbZc+Y+vnwnCUvOvJ203XVJayEyY2vwVr4Zrj3ZVkYTn/piat4L/nM7reCxCJuLh2QchOXLFvEIcJs4gHGxG+OiP1ziIDTCk9yqei9aKnUaWN/l+YhcNCc8zVfhVhRlHr2+9nwV7qHfrimS9C68fW+GJmCLOwJ28OyPb9CgC6b3cHEIe9qHdm/Ebo8ZYW9ZNOiXAxgXa7wuV09UssX24rexosJW2BzR+aKGyTNdMNuTQ8Lt40wfunoQUZMbsfWxURD9cUAVVT0N38tLdTp+GtOWMUsWLJgAYYk1EvvS9OnTc6FV/IEUZTSw7rMPsz4mhanvQlh2RruVxj1MvzdVs2RZcnIGfqMeOLYkI5Q9VCXmhaB8GkJ6w8U1TN7i6M2HaXbCp1gPHB5KAoLCjTN9jnV5mGIlD2XCPWhf3hnaeO4QLc46QCuzf8HEF0ZUGdNxJyUmraTRGfsLV4KdRFdoacnjwiWKpL8uXrDAFq1Sj1xse5yD7YyfYyo2EetKfE0Jb1V7Ex7AdOB/NnXxEixRieR0DvBlG9DYFdrfgwgO8yR8bq+wk2aMh7VwI3sw5cKLs6zAxGoguX1vkNfFvduZnQ2TqvBo25qpjcuNhb9yCRb3KOaiWJzBwz+NYGW/Ia4FTbigbLI9iOPgJIHJbU5S3isO391TzGQvLrDMaD7hrXuS+eT3sL74zyVBBDQw31JZyAvBE568dciQd2r6fCMxpsajRvOytQzf5cNI9QV2gLyGBzDdMLQAiDgHoP29i8hVCyS3+y6vxCba4F2xG4rA1KUpS2aV7lx5gUk0YvM6mt0lBaIzqXRFy9dwG8rl1myN9HJ8VxoA4VgmzNrl3egyDRckDl7Aw7HlZ2pgimCWSmk0evu6CFIQdNMwyozBjgk39tMOgcDpgTcj3+kTKJ3D23YznIdXweVnBVNpdfLixfghIpO+TE4+gJb/yj/QLm5C0IRBiov9ChpGAvKCedkfw1RuFQKL/NejKPPh+3nW9p5I0st4oZj1Ovk5ED2wFE8OVEen3B6fOwv983g8tjugw0+T43yHfzAT6Y5vLsOuxxjviu+Ksg6ZpRMEJMaUtAwvzkWdOnX6SivOqfbAmtv5WvIx/vAjdpp9ae4d02hEQ0572eSDlfy2nZ9Q+uaZsJTDfbHpjbSl2+PUXmftMiPnIHVdNKAskojesdMkeXvSqC3bwkVG0uDB/0NbV5tpL4+xPp8lJ39eDIvtiJ0hBJtA6DSD0aZwmispSg7CW2UWMHbEo6q7T5w4cZDv5y2Gceo3TpSMqVmzZif0Jx7CvQmL4ovheAwUJRf3Z5HPjQQ7oJEccWofBF32coCfMlqrVq32+O15xKJ4LOfUg7rgVhDXL8rlOlsgSXulgoJtPC5roJa1BSaHmpXwHFQ+s28w7XavGULqdU9plyEXHSF+ZER1yf9skW2ZRrRxui6esBcw6RUa/cOTaJdPzMOS7BSYYSFYNCI4UAU4AOOPTlLlt1ByQqfUXPaB1RWOzS2NCL5VAYXluuz9RD/OKw0W2WuGwKbu4y+CiLAJy8h2WLQuOHDpckBfYI7ddBZBNJ8Aa+zzKcT2xbpbPzLNba59/mrdq1i/zDKNw1ZAHlVdlR+kEQfO2IpXIBMcEBxwJAf0BSYnd3TGbPzni6j2pe0fU/+dxjXEk9gJFPP934l++dY+Wqxiktir1KBRqlU0Al5wQHCgcnDAv8Dkfcg/+jz+I5qFTUnxUtoPb9PwXcmF65XBYN167jDV/2oifC/5dneHJFXdQcz7MvEdUiIJDggOXBIcCCww7z+cS/kMvm5qQAtS0Bzz5dG8716hmFVP0mu/fE1nfLkVQPn0m0dIZ1unU4dlo4mOICi8c9JxkthdsIqfcw5JghLBAcGBUHMgoG9SIQH3Z2ygOR0fRPi3uXDQqGYLUdyXcl86TeSf2i1x0uQ11CauJTV2RdHKc5DNx7YQnd7lLOf0oo4jrr10H6ziIFAkwQHBgUuJA8EJTM6RUZsX0+xOj8MW/CbugocLhptn9+C42z2Fu30q7PgJBj58dSDl2dMQlmnha1K0JDggOOAUDgSekpemdO+A97HP/BJ1oWEKvAYmT9qX+BpYIlyISo8LcS04cIlwwJjAxCFVFNuaO7M/i81nEdsWF4HfBrurcOrh3povam2XigA9oknBAcGBCHDAmMDkBA5NlmlZq5dIVi4RoQmzPlOeGrKs1VM0yflbAyMwhkSTggOXDAeMC0zOGoSJp3s3vQQDEI9qZO4wnkrBYuwRV92jaNSmV3lo/EpBsiBScEBwIGQcMCcwi8hRYfxYiIDD/XF7KGQURgoxo91Yrx1BY3+Yh+UHsWYZqd9BtCs44CAOWBGYRd0Ys2kNMXdHYupnyHB8NJsgeM/7kELVsq6nsRtKIvoEASeqCA4IDlRxDlgXmJxBo9edor39E0mVRuKuohd6pWEiyyUm30P7+g2moT/bG3ik0vBAECo4IDigxwH7/Cm5BZ1oHs28fhOx/Fdw3Rsf/3Ha9KgKfz6nPQWGrCk0bvNmIvyJJDggOCA4UI4D9miYpZGOXbuD9tUaiLVNfGg1Ps7da60SQsBL38AZvQ99y4bTuI1CUpb+LcW14IDgQBkO2KdhlkZb5H6zjN5p+zXFRd9GPuUZCKZgjw4ojSlU1zDisB/hLvQM7avxmXAXChWbBV7BgarFgdAIzGIeTdiO8yYw1V1BX9Cxjr1Jdo1E0IrbYX2uXlwlzN9ncRjb1+RmMyg6fyUNLaQvzCSI5gQHBAcqKwdCKzCLudKbENUHe9EnTVpCLea1JiX2FpLUIXDX6QGHHZx+FsKkSgoOdEmHAT+NWEwajVq3N4StCdSCA4IDVZgD4RGYxQwsMgwhBBHxz3s0u2NjCMxEYq6+uO+ITz18LGqfSjam/4iALv9IijuNPAVL6Z4tvwBvlUo4FnY71hVMnXTokiRTcFWKgaIzggMmOMBMwIQGZGlCdTria4E4SC1IoitJjWqF6fMV0D/r4hiIOlhzxOl/krvQhZwxhFhTs3HNp9jHycUOY6/3PgTH2EE+aRcVNDpA9y+txO5NoWGxwCo4IDhgjQP/B6oro/7KpqfcAAAAAElFTkSuQmCC"
            />
          </defs>
          <use
            id="Layer"
            xlink:href="#image"
            x="0px"
            y="0px"
            width="232px"
            height="68px"
          />
        </svg>
      </div>
      <h1 class="h3 font-w700 mt-30 mb-10">
        Forgot Password ?
      </h1>
      <h2 class="h5 font-w400 text-muted mb-0">
        Please enter your email
      </h2>
    </div>
    <!-- END Header -->

    <!-- Sign In Form -->
    <form
      class="px-30"
      @submit.prevent="onSubmit"
    >
      <div class="form-group row">
        <div class="col-12">
          <p-form-input-material
            id="email"
            v-model="form.email"
            :errors="form.errors.get('email')"
            label="Email"
            name="email"
            @errors="form.errors.set('email', null)"
          />
        </div>
      </div>
      <div class="form-group text-center">
        <button
          type="submit"
          :disabled="isSaving"
          class="btn btn-sm btn-hero btn-primary"
        >
          <i
            v-show="isSaving"
            class="fa fa-asterisk fa-spin"
          /> Reset Password
        </button>
        <div class="mt-30">
          Remember your password ?
          <router-link
            class="link-effect text-muted mr-10 mb-5 d-inline-block"
            to="/auth/signin"
          >
            <i class="fa fa-user text-muted" /> Sign In
          </router-link>
        </div>
      </div>
    </form>
    <!-- END Sign In Form -->
  </div>
</template>

<script>
import Form from '@/utils/Form'
import { mapActions } from 'vuex'

export default {
  data () {
    return {
      isSaving: false,
      form: new Form({
        email: ''
      })
    }
  },
  methods: {
    ...mapActions('auth', ['resetPasswordRequest']),
    onSubmit () {
      this.isSaving = true
      this.resetPasswordRequest(this.form)
        .then(
          (response) => {
            this.isSaving = false
            this.$notification.success('Please check your email to reset your password')
            this.form.reset()
          },
          (error) => {
            this.isSaving = false
            this.form.errors.record(error.errors)
          }
        )
    }
  }
}
</script>
